- match:
    dependency_name: aws-sdk
    update_type: semver:minor

- match:
    dependency_type: development
    update_type: semver:minor

- match:
    dependency_type: production
    update_type: security:patch

- match:
    dependency_type: production
    update_type: semver:patch
